### ISSUE TITLE
Error: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by docbobo** [pl4nty/cloudflare-kubernetes-gateway#123]
Just tried installing this via `kubectl apply -k github.com/pl4nty/cloudflare-kubernetes-gateway/config/default` but I am getting `Error: container has runAsNonRoot and image will run as root` when the controller-manager tries to start up.

I tried changing runAsNonRoot to false, but then I get a `Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/manager": stat /manager: no such file or directory: unknown`

This is on Kubernetes v1.30.3 on ARM64.

**Comment by pl4nty** [comment]
Sorry about that, can you try `kubectl apply -k github.com/pl4nty/cloudflare-kubernetes-gateway//config/default?ref=v0.5.0`? There are some breaking changes on main that I haven't released yet. I've updated the README to match.

**Comment by docbobo** [comment]
Yes, that solves the particular problem. Thanks.
